export const DATA = {
  socialType: {
    axisY: [2.5, 2, 1.5, 1, 0.5, 0, -0.5, -1, -1.5, -2, -2.5],
    axisX: [
      'ИЛЭ',
      'ЛИИ',
      'СЭИ',
      'ЭСЭ',
      'СЛЭ',
      'ЛСИ',
      'ИЭИ',
      'ЭИЭ',
      'СЭЭ',
      'ЭСИ',
      'ИЛИ',
      'ЛИЭ',
      'ИЭЭ',
      'ЭИИ',
      'СЛИ',
      'ЛСЭ'
    ],
    data: [
      { real: 40, ref: null },
      { real: -80, ref: null },
      { real: 80, ref: null },
      { real: 20, ref: null },
      { real: 30, ref: null },
      { real: -60, ref: null },
      { real: -40, ref: null },
      { real: -80, ref: null },
      { real: 80, ref: null },
      { real: 20, ref: null },
      { real: 35, ref: null },
      { real: -65, ref: null },
      { real: 45, ref: null },
      { real: -85, ref: null },
      { real: 85, ref: null },
      { real: 25, ref: null }
    ]
  },
  socionicFeatures: {
    axisX: [1, 0, -1],
    data: [
      { real: 80, ref: null },
      { real: 20, ref: null },
      { real: -50, ref: null },
      { real: 60, ref: null },
      { real: 70, ref: null },
      { real: -10, ref: null },
      { real: -20, ref: null },
      { real: 45, ref: null },
      { real: 70, ref: null },
      { real: -80, ref: null },
      { real: 35, ref: null },
      { real: -25, ref: null },
      { real: 65, ref: null },
      { real: 75, ref: null },
      { real: -25, ref: null }
    ],
    leftLabel: [
      'интроверт',
      'динамик',
      'рационал',
      'сенсорик',
      'предусмотрительный',
      'центральный',
      'стратег',
      'этик',
      'упрямый',
      'нисходящий',
      'эмотивист',
      'элитарист',
      'негативист',
      'деклатим',
      'левый'
    ],
    rightLabel: [
      'экстраверт',
      'статик',
      'иррационал',
      'интуит',
      'беспечный',
      'периферийный',
      'тактик',
      'логик',
      'уступчивый',
      'восходящий',
      'конструктивист',
      'эгалитарист',
      'позитивист',
      'квестим',
      'правый'
    ]
  }
};
